from supabase import create_client, Client

supabase: Client = create_client("https://vnhtbjvcgatofbuctxiu.supabase.co", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZuaHRianZjZ2F0b2ZidWN0eGl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDgzOTQxNzIsImV4cCI6MjAyMzk3MDE3Mn0.ZNgcSiRI76LLvh-ietFjqsIBnWzr5Qq7dzzn7f2X0dM")